Repository canonical/kubeflow-volumes-operator, pull requests merged in 2024-07, with the labels that each got.

#139 Add logging relation to kubeflow-volumes
  lib/charms/loki_k8s/v1/loki_push_api.py
  metadata.yaml
  requirements-integration.in
  requirements-integration.txt
  requirements-unit.txt
  requirements.in
  requirements.txt
  src/charm.py
  tests/integration/test_charm.py
  tests/unit/test_operator.py
Labels: enhancement, Libraries: Out of sync

#140 ci: bump upload-charm action 2.4.0 -> 2.6.2
  .github/workflows/publish.yaml
Labels: Libraries: Out of sync

#142 ci(track): bump upload-charm action 2.4.0 -> 2.6.2
  .github/workflows/publish.yaml
Labels: Libraries: OK

#145 chore: bump image to 1.9.0
  metadata.yaml
Labels: Libraries: Out of sync

#144 chore: bump dashboard links lib
  lib/charms/kubeflow_dashboard/v0/kubeflow_dashboard_links.py
Labels: Libraries: Out of sync
